---
- name: Setup ecs
  hosts: all
  remote_user: aws_user
  sudo: yes
  vars:
    EPEL_GPG_KEY: http://ftp.riken.jp/Linux/fedora/epel/RPM-GPG-KEY-EPEL-6
    EPEL_URL: https://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
    JMETER_DL_URL: http://ftp.meisei-u.ac.jp/mirror/apache/dist//jmeter/binaries/apache-jmeter-2.11.zip
    JMETER_DL_DIR: '~/src/'
    JMETER_DL_PATH: '{{JMETER_DL_DIR}}/apache-jmeter-2.11.zip'

  tasks:
    - name: disallow password authentication
      lineinfile: dest=/etc/ssh/sshd_config regexp="^#PasswordAuthentication" line="PasswordAuthentication no" state=present
      notify: restart sshd

    - name: JDK add repository
      command: add-apt-repository ppa:webupd8team/java
    - name: apt update
      command: apt-get  update
    - name: apt upgrade
      command: apt-get  -y upgrade
    - name: install oracle-java8-installer
      command: apt-get -y install oracle-java8-installer
    - name: install install oracle-java8-set-default 
      command: apt-get -y install install oracle-java8-set-default 

    - name: jmeter directory setup
      file: path={{JMETER_DL_DIR}} state=directory owner=root group=root mode=755
    - name: download jmeter binary package
      command: 'wget -q -O {{JMETER_DL_PATH}} --no-cookies --no-check-certificate {{JMETER_DL_URL}} creates={{JMETER_DL_PATH}}'


  handlers:
    - name: restart sshd
      service: name=ssh state=restarted
