VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  box_name = "dummy"
  box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
  access_key = ENV['AWS_ACCESS_KEY']
  access_secret = ENV['AWS_SECRET_KEY']

  config.vm.box = box_name
  config.vm.box_url = box_url
  subnet_id = ENV['AWS_SUBNET_ID']
  private_ip_address = "10.0.1"
  ssh_username = "root"
  security_groups = [ENV['AWS_SECURITY_GROUP']]
  region = "ap-northeast-1"
  ami = "ami-e74b60e6"
  instance_type = "c3.large"


  (11..15).each do |num|
    config.vm.define "test#{num}" do |node|
      node.vm.provider :aws do |aws, override|
        aws.access_key_id = access_key
        aws.secret_access_key = access_secret
        aws.keypair_name = "moritata"
        aws.region = region
        aws.subnet_id = subnet_id
        aws.private_ip_address = "#{private_ip_address}.#{num}"
        aws.security_groups = security_groups
        aws.ami = ami
        aws.user_data = "#!/bin/sh\nsed -i 's/^.*requiretty/#Defaults requiretty/' /etc/sudoers\n "
        #aws.user_data = File.read("user_data.txt")
        aws.instance_type = instance_type
        aws.tags = {
          'Name' => "test#{num}",
        }
        override.ssh.username = ssh_username
        override.ssh.private_key_path = "~/.ssh/moritata.pem"

        config.vm.provision "ansible" do |ansible|
          ansible.playbook = "playbook.yml"
          ansible.inventory_path = "ansible/hosts/vagrant"
          ansible.verbose = true
        end

      end
    end
  end
end

