---
- name: Setup ecs
  hosts: all
  remote_user: aws_user
  sudo: yes
  vars:
    JAVA_DL_URL: http://download.oracle.com/otn-pub/java/jdk/8u5-b13/jdk-8u5-linux-x64.rpm
    JAVA_DL_DIR: /home/ec2-user/rpms/
    JAVA_DL_PATH: '{{JAVA_DL_DIR}}/jdk-8u5-linux-x64.rpm'
    EPEL_GPG_KEY: http://ftp.riken.jp/Linux/fedora/epel/RPM-GPG-KEY-EPEL-6
    EPEL_URL: https://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
    JMETER_DL_URL: http://ftp.meisei-u.ac.jp/mirror/apache/dist//jmeter/binaries/apache-jmeter-2.11.zip
    JMETER_DL_DIR: '/home/ec2-user/src/'
    JMETER_DL_PATH: '{{JMETER_DL_DIR}}/apache-jmeter-2.11.zip'

  tasks:
    - name: disallow password authentication
      lineinfile: dest=/etc/ssh/sshd_config regexp="^#PasswordAuthentication" line="PasswordAuthentication no" state=present
      notify: restart sshd
    - name: upload ssh private key
      template: src="~/.ssh/moritata.pem" dest="~/.ssh/moritata.pem"
    - name: mkdir /vagrant
      command: mkdir -p /vagrant
    - name: update yum
      command: yum -y update
    - name: yum groupinstall
      command: yum -y groupinstall "Development Tools"
    - name: yum developTool
      command: yum -y install ruby19 ruby19-devel emacs libxml2-devel libxslt-devel
    - name: python pip install
      command: yum -y install python26-pip
    - name: pip install virtualenv
      command: pip install virtualenv
    - name: pip install virtualenvwrapper
      command: pip install virtualenvwrapper
    - name: pip install ansible
      command: pip install ansible
    - name: pip install fabric
      command: pip install fabric
    - name: install vagrant
      command: rpm -ihv https://dl.bintray.com/mitchellh/vagrant/vagrant_1.6.5_x86_64.rpm
    - name: install vagrant plugin
      command: vagrant plugin install vagrant-aws

    - name: download directory create.
      file: path="{{JAVA_DL_DIR}}" state=directory owner=root group=root mode=755
    - name: download oracle jdk 1.8
      command: 'wget -q -O "{{JAVA_DL_PATH}}" --no-cookies --no-check-certificate --header "Cookie: oraclelicense=accept-securebackup-cookie" {{JAVA_DL_URL}} creates={{JAVA_DL_PATH}}'
      poll: 10
    - name: install oracle jdk
      yum: name={{JAVA_DL_PATH}}
    - name: jmeter directory setup
      file: path={{JMETER_DL_DIR}} state=directory owner=root group=root mode=755
    - name: download jmeter binary package
      command: 'wget -q -O {{JMETER_DL_PATH}} --no-cookies --no-check-certificate {{JMETER_DL_URL}} creates={{JMETER_DL_PATH}}'

  handlers:
    - name: restart sshd
      service: name=sshd state=restarted
