VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  box_name = "dummy"
  box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
  access_key = ENV['AWS_ACCESS_KEY']
  access_secret = ENV['AWS_SECRET_KEY']
  
  config.vm.box = box_name
  config.vm.box_url = box_url
  subnet_id = ENV['AWS_SUBNET_ID']
  private_ip_address = "10.0.0"
  ssh_username = "ec2-user"
  security_groups = ENV['AWS_SECURITY_GROUP']
  region = "ap-northeast-1"
  ami = "ami-4985b048"
  amigw = "ami-31c29e30"
  instance_type_ad = "t2.small"
  instance_type_gw = "c3.xlarge"


 (5..5).each do |num|
    config.vm.define "admin#{num}" do |node|
      node.vm.provider :aws do |aws, override|
        aws.access_key_id = access_key
        aws.secret_access_key = access_secret
        aws.keypair_name = "moritata"
        aws.region = region
        aws.subnet_id = subnet_id
        aws.private_ip_address = "#{private_ip_address}.#{num}"
        aws.elastic_ip = true
        aws.security_groups = security_groups
        aws.ami = ami
        aws.user_data = "#!/bin/sh\nsed -i 's/^.*requiretty/#Defaults requiretty/' /etc/sudoers\n "
        aws.instance_type = instance_type_ad
        aws.tags = {
          'Name' => "admin#{num}",
        }
        override.ssh.username = ssh_username
        override.ssh.private_key_path = "~/.ssh/moritata.pem"

      end
    end

    config.vm.define "nat-gw" do |node|
      node.vm.provider :aws do |aws, override|
        aws.access_key_id = access_key
        aws.secret_access_key = access_secret
        aws.keypair_name = "moritata"
        aws.region = region
        aws.subnet_id = subnet_id
        aws.private_ip_address = "#{private_ip_address}.250"
        aws.elastic_ip = true
        aws.security_groups = security_groups
        aws.ami = amigw
        aws.user_data = "#!/bin/sh\nsed -i 's/^.*requiretty/#Defaults requiretty/' /etc/sudoers\n "
        aws.instance_type = instance_type_gw
        aws.tags = {
          'Name' => "nat-gw",
        }
        override.ssh.username = ssh_username
        override.ssh.private_key_path = "~/.ssh/moritata.pem"

      end
    end

  end
end
